name = "FlatViews"
uuid = "7b36b3b9-274d-4a68-87d4-9634844f6493"
authors = ["Tamás K. Papp <tkpapp@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
DocStringExtensions = "0.9"
StaticArrays = "1"
julia = "1.8"
